AMQP_URI: "pyamqp://${RABBIT_USER:guest}:${RABBIT_PASS:guest}@${RABBIT_HOST:localhost}:5672/"
DB_URIS:
  "penawaran_kelas:Base": "postgresql+pg8000://${DB_USER:postgres}:${DB_PASS:postgres}@${DB_HOST:localhost}:5432/${DB_NAME:penawaran_kelas}"